apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - namespace: grafana-operator
  template:
    metadata:
      name: grafana-operator-{{name}}-{{namespace}}
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: oci://ghcr.io/grafana/helm-charts
        chart: grafana-operator
        targetRevision: v5.19.0
        helm:
          releaseName: grafana-operator
          valuesFiles:
            - https://github.com/omaralkhiri/monitoring-tools/blob/main/monitoring/grafana-values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true